Footer
Fatiuk/project-thewatchspot pull request #2
Opened 2023-05-06 10:57 UTC by aleksanderbutsak

2023-05-06 15:30 UTC, Fatiuk commented on src/css/footer.css
> +  padding-bottom: 40px;
padding-bottom: 20px;

2023-05-06 15:31 UTC, Fatiuk commented on src/css/footer.css
> +
@media screen and (min-width: 768px) {
  .footer {
    padding-top: 80px;
  }
}

@media screen and (min-width: 1280px) {
  .footer {
    padding-top: 104px;
    padding-bottom: 32px;
  }
}

2023-05-06 15:31 UTC, HalynaUser555 requested changes
потрібно зробити зміни з padding у класі FOOTER з медіа правилами

2023-05-07 07:39 UTC, HalynaUser555 approved these changes
ok

2023-05-07 18:43 UTC, closed without merging